### ISSUE TITLE
GitHub project short description "about"

### ISSUE THREAD

**Issue by stephaneghozzi** [aauss/epi-quark#3]
current version:

"Scoring the detection, labeling, and prediction performance of disease outbreak detection algorithms across different algorithm families."

proposal:

"Based on labeled data, multi-class and multi-label scoring of outbreak detection, annotation or prediction algorithms."

This should be coherent with documentation (https://github.com/aauss/epi-quark/blob/master/README.md, https://github.com/aauss/epi-quark/blob/master/docs/source/index.rst).

**Comment by aauss** [comment]
Thank you! Agreed and updated.
